### ISSUE TITLE
benchmark on imbalance data?

### ISSUE THREAD

**Issue by showkeyjar** [lixixibj/forecasting-with-time-series-imaging#4]
I read your paper <Forecasting with time series imaging>
It's very good idea, like 1d cnn + cnn, but more flexable.

I think this may need very strong signal value of labels

do you have test on very imbalance dataset?

for example: abnormal detection data or extreme weather data?

**Comment by feng-li** [comment]
We do not have experiments on very imbalanced data. Remedied for imbalanced labels should be easily plugged into our framework once we obtain the image features.
