### ISSUE TITLE
压缩包打不开

### ISSUE THREAD

**Issue by ABCDabcde1098234** [lixixibj/forecasting-with-time-series-imaging#5]
你好，文件件里面的压缩包已经过期，是否可以重新更一下？

**Comment by feng-li** [comment]
请检查以下是否下载完整或者请指出哪个压缩包打不开，我这里显示都能打开。

**Comment by ABCDabcde1098234** [comment]
你好，我所有的压缩文件都打不开，! E:\python\forecasting-with-time-series-imaging-master\forecasting-with-time-series-imaging-master\9_methods_forecasts_and_owa\9_methods_prediction_value_M4.zip: 这个压缩文件格式未知或者数据已经被损坏
! 没有找到压缩文件

每一个都这么显示

**Comment by feng-li** [comment]
数据太大，GITHUB使用大文件系统存储了，请参考README使用命令行下载。
